# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/martin/projects/Q5LegacyStyle

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/martin/projects/Q5LegacyStyle

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/martin/projects/Q5LegacyStyle/CMakeFiles /home/martin/projects/Q5LegacyStyle//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/martin/projects/Q5LegacyStyle/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named qlegacystyle

# Build rule for target.
qlegacystyle: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 qlegacystyle
.PHONY : qlegacystyle

# fast build rule for target.
qlegacystyle/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qlegacystyle.dir/build.make CMakeFiles/qlegacystyle.dir/build
.PHONY : qlegacystyle/fast

#=============================================================================
# Target rules for targets named widgetgallery

# Build rule for target.
widgetgallery: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 widgetgallery
.PHONY : widgetgallery

# fast build rule for target.
widgetgallery/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/widgetgallery.dir/build.make CMakeFiles/widgetgallery.dir/build
.PHONY : widgetgallery/fast

#=============================================================================
# Target rules for targets named qlegacystyle_autogen

# Build rule for target.
qlegacystyle_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 qlegacystyle_autogen
.PHONY : qlegacystyle_autogen

# fast build rule for target.
qlegacystyle_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qlegacystyle_autogen.dir/build.make CMakeFiles/qlegacystyle_autogen.dir/build
.PHONY : qlegacystyle_autogen/fast

#=============================================================================
# Target rules for targets named widgetgallery_autogen

# Build rule for target.
widgetgallery_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 widgetgallery_autogen
.PHONY : widgetgallery_autogen

# fast build rule for target.
widgetgallery_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/widgetgallery_autogen.dir/build.make CMakeFiles/widgetgallery_autogen.dir/build
.PHONY : widgetgallery_autogen/fast

qlegacystyle_autogen/mocs_compilation.o: qlegacystyle_autogen/mocs_compilation.cpp.o
.PHONY : qlegacystyle_autogen/mocs_compilation.o

# target to build an object file
qlegacystyle_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qlegacystyle.dir/build.make CMakeFiles/qlegacystyle.dir/qlegacystyle_autogen/mocs_compilation.cpp.o
.PHONY : qlegacystyle_autogen/mocs_compilation.cpp.o

qlegacystyle_autogen/mocs_compilation.i: qlegacystyle_autogen/mocs_compilation.cpp.i
.PHONY : qlegacystyle_autogen/mocs_compilation.i

# target to preprocess a source file
qlegacystyle_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qlegacystyle.dir/build.make CMakeFiles/qlegacystyle.dir/qlegacystyle_autogen/mocs_compilation.cpp.i
.PHONY : qlegacystyle_autogen/mocs_compilation.cpp.i

qlegacystyle_autogen/mocs_compilation.s: qlegacystyle_autogen/mocs_compilation.cpp.s
.PHONY : qlegacystyle_autogen/mocs_compilation.s

# target to generate assembly for a file
qlegacystyle_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qlegacystyle.dir/build.make CMakeFiles/qlegacystyle.dir/qlegacystyle_autogen/mocs_compilation.cpp.s
.PHONY : qlegacystyle_autogen/mocs_compilation.cpp.s

src/drawutil.o: src/drawutil.cpp.o
.PHONY : src/drawutil.o

# target to build an object file
src/drawutil.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qlegacystyle.dir/build.make CMakeFiles/qlegacystyle.dir/src/drawutil.cpp.o
.PHONY : src/drawutil.cpp.o

src/drawutil.i: src/drawutil.cpp.i
.PHONY : src/drawutil.i

# target to preprocess a source file
src/drawutil.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qlegacystyle.dir/build.make CMakeFiles/qlegacystyle.dir/src/drawutil.cpp.i
.PHONY : src/drawutil.cpp.i

src/drawutil.s: src/drawutil.cpp.s
.PHONY : src/drawutil.s

# target to generate assembly for a file
src/drawutil.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qlegacystyle.dir/build.make CMakeFiles/qlegacystyle.dir/src/drawutil.cpp.s
.PHONY : src/drawutil.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/widgetgallery.dir/build.make CMakeFiles/widgetgallery.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/widgetgallery.dir/build.make CMakeFiles/widgetgallery.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/widgetgallery.dir/build.make CMakeFiles/widgetgallery.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/qlegacystyle.o: src/qlegacystyle.cpp.o
.PHONY : src/qlegacystyle.o

# target to build an object file
src/qlegacystyle.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qlegacystyle.dir/build.make CMakeFiles/qlegacystyle.dir/src/qlegacystyle.cpp.o
.PHONY : src/qlegacystyle.cpp.o

src/qlegacystyle.i: src/qlegacystyle.cpp.i
.PHONY : src/qlegacystyle.i

# target to preprocess a source file
src/qlegacystyle.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qlegacystyle.dir/build.make CMakeFiles/qlegacystyle.dir/src/qlegacystyle.cpp.i
.PHONY : src/qlegacystyle.cpp.i

src/qlegacystyle.s: src/qlegacystyle.cpp.s
.PHONY : src/qlegacystyle.s

# target to generate assembly for a file
src/qlegacystyle.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qlegacystyle.dir/build.make CMakeFiles/qlegacystyle.dir/src/qlegacystyle.cpp.s
.PHONY : src/qlegacystyle.cpp.s

src/qlegacystyleplugin.o: src/qlegacystyleplugin.cpp.o
.PHONY : src/qlegacystyleplugin.o

# target to build an object file
src/qlegacystyleplugin.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qlegacystyle.dir/build.make CMakeFiles/qlegacystyle.dir/src/qlegacystyleplugin.cpp.o
.PHONY : src/qlegacystyleplugin.cpp.o

src/qlegacystyleplugin.i: src/qlegacystyleplugin.cpp.i
.PHONY : src/qlegacystyleplugin.i

# target to preprocess a source file
src/qlegacystyleplugin.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qlegacystyle.dir/build.make CMakeFiles/qlegacystyle.dir/src/qlegacystyleplugin.cpp.i
.PHONY : src/qlegacystyleplugin.cpp.i

src/qlegacystyleplugin.s: src/qlegacystyleplugin.cpp.s
.PHONY : src/qlegacystyleplugin.s

# target to generate assembly for a file
src/qlegacystyleplugin.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qlegacystyle.dir/build.make CMakeFiles/qlegacystyle.dir/src/qlegacystyleplugin.cpp.s
.PHONY : src/qlegacystyleplugin.cpp.s

src/widgetgallery.o: src/widgetgallery.cpp.o
.PHONY : src/widgetgallery.o

# target to build an object file
src/widgetgallery.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/widgetgallery.dir/build.make CMakeFiles/widgetgallery.dir/src/widgetgallery.cpp.o
.PHONY : src/widgetgallery.cpp.o

src/widgetgallery.i: src/widgetgallery.cpp.i
.PHONY : src/widgetgallery.i

# target to preprocess a source file
src/widgetgallery.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/widgetgallery.dir/build.make CMakeFiles/widgetgallery.dir/src/widgetgallery.cpp.i
.PHONY : src/widgetgallery.cpp.i

src/widgetgallery.s: src/widgetgallery.cpp.s
.PHONY : src/widgetgallery.s

# target to generate assembly for a file
src/widgetgallery.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/widgetgallery.dir/build.make CMakeFiles/widgetgallery.dir/src/widgetgallery.cpp.s
.PHONY : src/widgetgallery.cpp.s

widgetgallery_autogen/mocs_compilation.o: widgetgallery_autogen/mocs_compilation.cpp.o
.PHONY : widgetgallery_autogen/mocs_compilation.o

# target to build an object file
widgetgallery_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/widgetgallery.dir/build.make CMakeFiles/widgetgallery.dir/widgetgallery_autogen/mocs_compilation.cpp.o
.PHONY : widgetgallery_autogen/mocs_compilation.cpp.o

widgetgallery_autogen/mocs_compilation.i: widgetgallery_autogen/mocs_compilation.cpp.i
.PHONY : widgetgallery_autogen/mocs_compilation.i

# target to preprocess a source file
widgetgallery_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/widgetgallery.dir/build.make CMakeFiles/widgetgallery.dir/widgetgallery_autogen/mocs_compilation.cpp.i
.PHONY : widgetgallery_autogen/mocs_compilation.cpp.i

widgetgallery_autogen/mocs_compilation.s: widgetgallery_autogen/mocs_compilation.cpp.s
.PHONY : widgetgallery_autogen/mocs_compilation.s

# target to generate assembly for a file
widgetgallery_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/widgetgallery.dir/build.make CMakeFiles/widgetgallery.dir/widgetgallery_autogen/mocs_compilation.cpp.s
.PHONY : widgetgallery_autogen/mocs_compilation.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... qlegacystyle_autogen"
	@echo "... widgetgallery_autogen"
	@echo "... qlegacystyle"
	@echo "... widgetgallery"
	@echo "... qlegacystyle_autogen/mocs_compilation.o"
	@echo "... qlegacystyle_autogen/mocs_compilation.i"
	@echo "... qlegacystyle_autogen/mocs_compilation.s"
	@echo "... src/drawutil.o"
	@echo "... src/drawutil.i"
	@echo "... src/drawutil.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/qlegacystyle.o"
	@echo "... src/qlegacystyle.i"
	@echo "... src/qlegacystyle.s"
	@echo "... src/qlegacystyleplugin.o"
	@echo "... src/qlegacystyleplugin.i"
	@echo "... src/qlegacystyleplugin.s"
	@echo "... src/widgetgallery.o"
	@echo "... src/widgetgallery.i"
	@echo "... src/widgetgallery.s"
	@echo "... widgetgallery_autogen/mocs_compilation.o"
	@echo "... widgetgallery_autogen/mocs_compilation.i"
	@echo "... widgetgallery_autogen/mocs_compilation.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

